<a href="https://colab.research.google.com/github/jakemacbeth/Timberwolves-MidSeason_Review/blob/main/reports/Defense_Against_Top_Offenses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [121]:
import sys
from pathlib import Path
import pandas as pd
from sqlalchemy import text
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [122]:
base = "https://raw.githubusercontent.com/jakemacbeth/Timberwolves-MidSeason_Review/main/data/"

wolves_df = pd.read_csv(base + "teambox_bucket_teams.csv")
opp_df = pd.read_csv(base + "opponnent_boxscores_bucketed.csv")
teambox = pd.read_csv(base + "teambox_pergame.csv")

In [123]:
wolves_df.columns.tolist()

['game_id',
 'opp_bucket',
 'off_rank',
 'def_rank',
 'opponent_team_name',
 'game_id-2',
 'team_id',
 'season',
 'is_home',
 'opponent_team_id',
 'minutes',
 'pts',
 'fgm',
 'fga',
 'fg3m',
 'fg3a',
 'ftm',
 'fta',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'off_rating',
 'def_rating',
 'net_rating',
 'pace',
 'ts_pct',
 'last_updated_at']

In [124]:
wolves_df = wolves_df.drop(columns=[
 'game_id-2',
 'season',
 'is_home',
 'minutes',
 'last_updated_at']
)

In [125]:
wolves_df.columns.tolist()

['game_id',
 'opp_bucket',
 'off_rank',
 'def_rank',
 'opponent_team_name',
 'team_id',
 'opponent_team_id',
 'pts',
 'fgm',
 'fga',
 'fg3m',
 'fg3a',
 'ftm',
 'fta',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'off_rating',
 'def_rating',
 'net_rating',
 'pace',
 'ts_pct']

In [126]:
opp_df.columns.tolist()

['game_id',
 'opp_bucket',
 'off_rank',
 'def_rank',
 'opponent_team_name',
 'wolves_win',
 'game_id-2',
 'team_id',
 'season',
 'is_home',
 'opponent_team_id',
 'minutes',
 'pts',
 'fgm',
 'fga',
 'fg3m',
 'fg3a',
 'ftm',
 'fta',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'off_rating',
 'def_rating',
 'net_rating',
 'pace',
 'ts_pct',
 'last_updated_at']

In [127]:
opp_df = opp_df.drop(columns=[
 'opponent_team_name',
 'season',
 'opponent_team_id',
 'last_updated_at']
)

In [128]:
opp_df.columns.tolist()

['game_id',
 'opp_bucket',
 'off_rank',
 'def_rank',
 'wolves_win',
 'game_id-2',
 'team_id',
 'is_home',
 'minutes',
 'pts',
 'fgm',
 'fga',
 'fg3m',
 'fg3a',
 'ftm',
 'fta',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'off_rating',
 'def_rating',
 'net_rating',
 'pace',
 'ts_pct']

In [129]:
stat_cols = ['pts',
 'fgm',
 'fga',
 'fg3m',
 'fg3a',
 'ftm',
 'fta',
 'oreb',
 'dreb',
 'reb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'off_rating',
 'def_rating',
 'net_rating',
 'pace',
 'ts_pct']

bucket_means = (
    opp_df
    .groupby(['opp_bucket', 'wolves_win'])[stat_cols]
    .mean()
    .reset_index()
    .round(1)
)
bucket_means

,opp_bucket,wolves_win,pts,fgm,fga,fg3m,fg3a,ftm,fta,oreb,...,ast,stl,blk,tov,pf,off_rating,def_rating,net_rating,pace,ts_pct
0,Top8 Off / Bottom22 Def,False,135.0,48.4,93.2,16.0,34.2,22.2,25.8,12.0,...,30.8,7.4,5.0,12.8,20.0,129.0,117.9,11.1,102.2,0.6
1,Top8 Off / Bottom22 Def,True,113.0,44.5,95.0,11.0,31.5,13.0,18.0,13.5,...,25.5,8.5,2.0,15.5,19.0,109.6,118.2,-8.6,103.5,0.6
2,Top8 Off / Top8 Def,False,116.3,41.3,86.0,11.3,30.7,22.3,33.3,10.7,...,24.3,8.0,4.3,10.0,22.7,117.5,112.1,5.4,99.0,0.6
3,Top8 Off / Top8 Def,True,109.6,39.6,89.2,11.8,37.4,18.6,21.8,11.0,...,20.6,8.8,4.8,12.0,20.6,111.6,119.0,-7.5,98.3,0.6

In [130]:
diagnostic_df = bucket_means.drop(columns=['pace','ts_pct', 'net_rating', 'oreb', 'pf'])
diagnostic_df

,opp_bucket,wolves_win,pts,fgm,fga,fg3m,fg3a,ftm,fta,dreb,reb,ast,stl,blk,tov,off_rating,def_rating
0,Top8 Off / Bottom22 Def,False,135.0,48.4,93.2,16.0,34.2,22.2,25.8,31.8,43.8,30.8,7.4,5.0,12.8,129.0,117.9
1,Top8 Off / Bottom22 Def,True,113.0,44.5,95.0,11.0,31.5,13.0,18.0,33.0,46.5,25.5,8.5,2.0,15.5,109.6,118.2
2,Top8 Off / Top8 Def,False,116.3,41.3,86.0,11.3,30.7,22.3,33.3,30.7,41.3,24.3,8.0,4.3,10.0,117.5,112.1
3,Top8 Off / Top8 Def,True,109.6,39.6,89.2,11.8,37.4,18.6,21.8,31.6,42.6,20.6,8.8,4.8,12.0,111.6,119.0

In [131]:
results = diagnostic_df.drop(columns=['dreb', 'reb', 'blk', 'tov', 'stl', 'ast', 'off_rating', 'def_rating', 'pts'])
results.head()

                opp_bucket  wolves_win   fgm   fga  fg3m  fg3a   ftm   fta
0  Top8 Off / Bottom22 Def       False  48.4  93.2  16.0  34.2  22.2  25.8
1  Top8 Off / Bottom22 Def        True  44.5  95.0  11.0  31.5  13.0  18.0
2      Top8 Off / Top8 Def       False  41.3  86.0  11.3  30.7  22.3  33.3
3      Top8 Off / Top8 Def        True  39.6  89.2  11.8  37.4  18.6  21.8

In [132]:
wolves_id = 1610612750

# filter first
teambox_filtered = teambox[
    (teambox['opponent_team_id'] != wolves_id) &
    (teambox['opponent_team_id'].isin(opp_df['team_id']))
]

# bring bucket and win labels
opp_keys = opp_df[['team_id','wolves_win','opp_bucket']].drop_duplicates()

teambox_filtered = teambox_filtered.merge(opp_keys, on='team_id', how='left')

stats = ['fgm','fga','fg3m','fg3a','ftm','fta']

team_avg = (
    teambox_filtered
    .groupby(['opp_bucket','wolves_win'])[stats]
    .mean()
    .round(1)
    .reset_index()
)
team_avg

                opp_bucket  wolves_win   fgm   fga  fg3m  fg3a   ftm   fta
0  Top8 Off / Bottom22 Def       False  41.3  89.1  15.1  40.9  18.5  23.9
1  Top8 Off / Bottom22 Def        True  41.3  89.5  15.5  42.0  17.5  22.7
2      Top8 Off / Top8 Def       False  40.9  89.4  13.3  36.5  18.5  23.9
3      Top8 Off / Top8 Def        True  40.9  90.2  14.0  41.1  17.1  21.6

In [133]:
results_fmt = results.rename(columns={
    'opp_bucket': 'Opponent Bucket',
    'wolves_win': 'Wolves Win',
    'fgm': 'FGM',
    'fga': 'FGA',
    'fg3m': 'FG3M',
    'fg3a': 'FG3A',
    'ftm': 'FTM',
    'fta': 'FTA'
})
results_styled = (results_fmt
 .style
 .format(precision=2)
 .hide(axis='index')
 .set_table_styles([
     {'selector': 'thead th',
      'props': [('background-color', '#1f4e79'),
                ('color', 'white'),
                ('font-weight', 'bold'),
                ('text-align', 'center')]},
     {'selector': 'tbody td',
      'props': [('text-align', 'center')]}
 ])
 .set_properties(**{'border': '1px solid #ddd'})
 .set_table_attributes('style="border-collapse:collapse;width:100%;"')
 .apply(lambda _: ['background-color: #f6f8fa' if i % 2 else '' for i in range(len(results_fmt))],
        axis=0)
)
stats = ['FGM','FGA','FG3M','FG3A','FTM','FTA']

results_styled.background_gradient(
    subset=stats,
    cmap='Blues'
).format({col:"{:.1f}" for col in stats}).set_caption(
    "Opponent Shooting Averages vs Wolves")

In [134]:
wolves_id = 1610612750

# filter first
teambox_filtered = teambox[
    (teambox['opponent_team_id'] != wolves_id) &
    (teambox['opponent_team_id'].isin(opp_df['team_id']))
]

# bring bucket and win labels
opp_keys = opp_df[['team_id','wolves_win','opp_bucket']].drop_duplicates()

teambox_filtered = teambox_filtered.merge(opp_keys, on='team_id', how='left')

stats = ['fgm','fga','fg3m','fg3a','ftm','fta']

team_avg = (
    teambox_filtered
    .groupby(['opp_bucket','wolves_win'])[stats]
    .mean()
    .round(1)
    .reset_index()
)
team_avg

                opp_bucket  wolves_win   fgm   fga  fg3m  fg3a   ftm   fta
0  Top8 Off / Bottom22 Def       False  41.3  89.1  15.1  40.9  18.5  23.9
1  Top8 Off / Bottom22 Def        True  41.3  89.5  15.5  42.0  17.5  22.7
2      Top8 Off / Top8 Def       False  40.9  89.4  13.3  36.5  18.5  23.9
3      Top8 Off / Top8 Def        True  40.9  90.2  14.0  41.1  17.1  21.6

In [135]:
stats = ['fgm','fga','fg3m','fg3a','ftm','fta']

results_i = results.set_index(['opp_bucket','wolves_win'])
team_avg_i = team_avg.set_index(['opp_bucket','wolves_win'])
impact = results_i[stats] - team_avg_i[stats]
impact = impact.reset_index()
impact

                opp_bucket  wolves_win  fgm  fga  fg3m  fg3a  ftm  fta
0  Top8 Off / Bottom22 Def       False  7.1  4.1   0.9  -6.7  3.7  1.9
1  Top8 Off / Bottom22 Def        True  3.2  5.5  -4.5 -10.5 -4.5 -4.7
2      Top8 Off / Top8 Def       False  0.4 -3.4  -2.0  -5.8  3.8  9.4
3      Top8 Off / Top8 Def        True -1.3 -1.0  -2.2  -3.7  1.5  0.2

In [143]:
impact_fmt = impact.rename(columns={
    'opp_bucket': 'Opponent Bucket',
    'wolves_win': 'Wolves Win',
    'fgm': 'FGM',
    'fga': 'FGA',
    'fg3m': 'FG3M',
    'fg3a': 'FG3A',
    'ftm': 'FTM',
    'fta': 'FTA'
})
impact_styled = (impact_fmt
 .style
 .format(precision=1)
 .hide(axis='index')
 .set_table_styles([
     {'selector': 'thead th',
      'props': [('background-color', '#1f4e79'),
                ('color', 'white'),
                ('font-weight', 'bold'),
                ('text-align', 'center')]},
     {'selector': 'tbody td',
      'props': [('text-align', 'center')]}
 ])
 .set_properties(**{'border': '1px solid #ddd'})
 .set_table_attributes('style="border-collapse:collapse;width:100%;"')
 .apply(lambda _: ['background-color: #f6f8fa' if i % 2 else '' for i in range(len(impact_fmt))],
        axis=0)
 .set_caption("Opponent Shooting Vs Timberwolves Relative to Season Average")
)
impact_styled